<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Src\Games\Domain\Models\Game;

class ClassicGamesSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            [
                'name' => 'Truco',
                'description' => 'Juego de cartas tradicional argentino para equipos',
                'number_of_players' => 4,
                'turn_duration' => null,
                'round_duration' => 20,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 30,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => true,
                'min_team_length' => 2,
                'max_team_length' => 2,
                'icon' => 'CardsThree',
                'color' => '#ef4444',
                'bg_color' => '#fee2e2',
                'rules' => "El primer equipo en llegar a 30 puntos gana.\nSe juega con 40 cartas españolas.\nValor de las jugadas: Envido (hasta 33 puntos), Truco (1, 2 o 3 puntos).",
                'user_id' => 0,
            ],
            [
                'name' => 'Generala',
                'description' => 'Juego de dados clásico',
                'number_of_players' => 4,
                'turn_duration' => 60,
                'round_duration' => 5,
                'rounds' => 10,
                'starting_points' => 0,
                'finishing_points' => 1000,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 1,
                'icon' => 'DiceFive',
                'color' => '#3b82f6',
                'bg_color' => '#dbeafe',
                'rules' => "Cada jugador tira 5 dados hasta 3 veces por turno.\nObjetivos: Escalera, Full, Póker, Generala.\nGenerala servida: 100 puntos.\nEl jugador con más puntos al final gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Dardos 501',
                'description' => 'Juego de dardos profesional - Empieza en 501 y baja a 0',
                'number_of_players' => 2,
                'turn_duration' => 90,
                'round_duration' => 10,
                'rounds' => 20,
                'starting_points' => 501,
                'finishing_points' => 0,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 2,
                'icon' => 'Target',
                'color' => '#f97316',
                'bg_color' => '#ffedd5',
                'rules' => "Cada jugador comienza con 501 puntos.\nTiras 3 dardos por turno y restas el puntaje.\nDebes llegar exactamente a 0 y el último dardo debe ser doble.\nSi pasas de 0, el turno no cuenta.",
                'user_id' => 0,
            ],
            [
                'name' => 'Escoba de 15',
                'description' => 'Juego de cartas español tradicional',
                'number_of_players' => 4,
                'turn_duration' => null,
                'round_duration' => 15,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 15,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 2,
                'icon' => 'CardsThree',
                'color' => '#10b981',
                'bg_color' => '#d1fae5',
                'rules' => "Se juega con baraja española de 40 cartas.\nCaptura cartas de la mesa sumando 15.\nPuntos por: Escobas (1p), Cartas (1p), Oros (1p), Siete de oro (1p).\nPrimer jugador en 15 puntos gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Buraco',
                'description' => 'Juego de cartas para equipos similar a Canasta',
                'number_of_players' => 4,
                'turn_duration' => null,
                'round_duration' => 30,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 3000,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => true,
                'min_team_length' => 2,
                'max_team_length' => 2,
                'icon' => 'CardsThree',
                'color' => '#a855f7',
                'bg_color' => '#f3e8ff',
                'rules' => "Se juega con 2 mazos de cartas.\nForma juegos de 3 o más cartas del mismo valor.\nBuraco limpio (sin comodines): 500 puntos.\nBuraco sucio (con comodines): 300 puntos.\nPrimer equipo en 3000 puntos gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Ping Pong',
                'description' => 'Tenis de mesa - Primer jugador en 11 puntos gana',
                'number_of_players' => 2,
                'turn_duration' => null,
                'round_duration' => 10,
                'rounds' => 5,
                'starting_points' => 0,
                'finishing_points' => 11,
                'is_winning' => true,
                'has_turns' => false,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 2,
                'icon' => 'TennisBall',
                'color' => '#84cc16',
                'bg_color' => '#ecfccb',
                'rules' => "Primer jugador en 11 puntos gana el set.\nDebes ganar por 2 puntos de diferencia.\nSe juega al mejor de 5 sets (primero en ganar 3).\nServicio cambia cada 2 puntos.",
                'user_id' => 0,
            ],
            [
                'name' => 'Pool 8-Ball',
                'description' => 'Billar clásico - Emboca todas tus bolas y luego la 8',
                'number_of_players' => 2,
                'turn_duration' => null,
                'round_duration' => 20,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 8,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 1,
                'icon' => 'Target',
                'color' => '#14b8a6',
                'bg_color' => '#ccfbf1',
                'rules' => "Un jugador tiene las bolas lisas (1-7), el otro las rayadas (9-15).\nDebes embocar todas tus bolas antes que tu oponente.\nDespués de embocar todas tus bolas, emboca la bola 8 para ganar.\nSi embocas la 8 antes de tiempo, pierdes.",
                'user_id' => 0,
            ],
            [
                'name' => 'Fútbol 5',
                'description' => 'Fútbol 5 - Equipo con más goles gana',
                'number_of_players' => 10,
                'turn_duration' => null,
                'round_duration' => 25,
                'rounds' => 2,
                'starting_points' => 0,
                'finishing_points' => 100,
                'is_winning' => true,
                'has_turns' => false,
                'has_teams' => true,
                'min_team_length' => 4,
                'max_team_length' => 6,
                'icon' => 'Football',
                'color' => '#10b981',
                'bg_color' => '#d1fae5',
                'rules' => "2 tiempos de 25 minutos cada uno.\nCada gol suma 1 punto.\nEl equipo con más goles al final del partido gana.\nEn caso de empate, se pueden jugar penales.",
                'user_id' => 0,
            ],
            [
                'name' => 'Chinchón',
                'description' => 'Juego de cartas español - El primero en llegar a 100 puntos PIERDE',
                'number_of_players' => 4,
                'turn_duration' => null,
                'round_duration' => 10,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 100,
                'is_winning' => false,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 1,
                'icon' => 'CardsThree',
                'color' => '#f43f5e',
                'bg_color' => '#ffe4e6',
                'rules' => "Se juega con baraja española de 40 cartas.\nForma escaleras o tríos para bajar puntos.\nChinchón (todas las cartas en juegos): 0 puntos y -10 al rival.\nEl jugador que llega a 100 puntos PIERDE.\nÚltimo jugador que queda en pie gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Volleyball',
                'description' => 'Voleibol de playa o cancha - Primer equipo en 25 puntos gana',
                'number_of_players' => 12,
                'turn_duration' => null,
                'round_duration' => 20,
                'rounds' => 5,
                'starting_points' => 0,
                'finishing_points' => 25,
                'is_winning' => true,
                'has_turns' => false,
                'has_teams' => true,
                'min_team_length' => 6,
                'max_team_length' => 6,
                'icon' => 'Volleyball',
                'color' => '#f97316',
                'bg_color' => '#ffedd5',
                'rules' => "Primer equipo en 25 puntos gana el set (debe ganar por 2).\nSe juega al mejor de 5 sets.\nEl 5to set (si es necesario) se juega a 15 puntos.\nCada punto se anota cuando el balón toca el suelo del campo contrario.",
                'user_id' => 0,
            ],
            [
                'name' => 'Uno',
                'description' => 'Juego de cartas clásico - El primero que se queda sin cartas gana',
                'number_of_players' => 6,
                'turn_duration' => 30,
                'round_duration' => 15,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 500,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 1,
                'icon' => 'CardsThree',
                'color' => '#f59e0b',
                'bg_color' => '#fef3c7',
                'rules' => "Deshazte de todas tus cartas antes que los demás.\nDebes coincidir color, número o símbolo.\nCartas especiales: +2, +4, Reversa, Salto.\nDi ¡UNO! cuando te quede una carta.\nPrimer jugador en 500 puntos gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Dominó',
                'description' => 'Juego de fichas clásico - Primer jugador/equipo en 100 puntos gana',
                'number_of_players' => 4,
                'turn_duration' => 45,
                'round_duration' => 15,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 100,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => true,
                'min_team_length' => 2,
                'max_team_length' => 2,
                'icon' => 'GameController',
                'color' => '#8b5cf6',
                'bg_color' => '#ede9fe',
                'rules' => "28 fichas con combinaciones del 0 al 6.\nColoca fichas conectando números iguales.\nSi no puedes jugar, pasas turno.\nPrimero en deshacerse de todas las fichas gana la ronda.\nPrimer equipo en 100 puntos gana el juego.",
                'user_id' => 0,
            ],
            [
                'name' => 'Basketball 21',
                'description' => 'Básquet de calle - Primer jugador en 21 puntos gana',
                'number_of_players' => 3,
                'turn_duration' => null,
                'round_duration' => 15,
                'rounds' => 1,
                'starting_points' => 0,
                'finishing_points' => 21,
                'is_winning' => true,
                'has_turns' => false,
                'has_teams' => false,
                'min_team_length' => 1,
                'max_team_length' => 1,
                'icon' => 'Basketball',
                'color' => '#f97316',
                'bg_color' => '#ffedd5',
                'rules' => "Primer jugador en anotar exactamente 21 puntos gana.\nSi pasas de 21, vuelves a 15 puntos.\nCanastas dentro del arco: 1 punto.\nCanastas desde afuera del arco: 2 puntos.\nDebes ganar por 2 puntos.",
                'user_id' => 0,
            ],
            [
                'name' => 'Tejo',
                'description' => 'Juego tradicional colombiano - Lanza discos de metal a un blanco',
                'number_of_players' => 4,
                'turn_duration' => 60,
                'round_duration' => 10,
                'rounds' => 6,
                'starting_points' => 0,
                'finishing_points' => 27,
                'is_winning' => true,
                'has_turns' => true,
                'has_teams' => true,
                'min_team_length' => 2,
                'max_team_length' => 2,
                'icon' => 'Target',
                'color' => '#f59e0b',
                'bg_color' => '#fef3c7',
                'rules' => "Lanza tejos (discos de metal) a un tablero.\nMecha (hacer explotar pólvora): 9 puntos.\nBocín (centro del tablero): 6 puntos.\nMano (tejo más cercano): 3 puntos.\nPrimer equipo en 27 puntos gana.",
                'user_id' => 0,
            ],
            [
                'name' => 'Paddle',
                'description' => 'Tenis con paredes - Primer equipo en ganar 2 sets gana',
                'number_of_players' => 4,
                'turn_duration' => null,
                'round_duration' => 20,
                'rounds' => 3,
                'starting_points' => 0,
                'finishing_points' => 6,
                'is_winning' => true,
                'has_turns' => false,
                'has_teams' => true,
                'min_team_length' => 2,
                'max_team_length' => 2,
                'icon' => 'TennisBall',
                'color' => '#06b6d4',
                'bg_color' => '#cffafe',
                'rules' => "Similar al tenis pero con paredes que están en juego.\nPrimer equipo en ganar 6 games gana el set.\nSe juega al mejor de 3 sets.\nSistema de puntuación: 15, 30, 40, juego.\nTiebreak a 7 puntos si hay empate 6-6.",
                'user_id' => 0,
            ],
        ];

        foreach ($games as $game) {
            Game::create($game);
        }
    }

}
