services:
  # --- APP Laravel ---
  - type: web
    name: laravel-app
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      cp .env.example .env
      php artisan key:generate
    startCommand: |
      php artisan migrate --force || true
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://laravel-app.onrender.com

      # --- Database ---
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService: postgres
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: laravel
      - key: DB_PASSWORD
        value: laravel

      # --- Redis ---
      - key: REDIS_HOST
        fromService: redis
      - key: REDIS_PORT
        value: 6379

      # --- MinIO ---
      - key: FILESYSTEM_DISK
        value: s3
      - key: AWS_ACCESS_KEY_ID
        value: sail
      - key: AWS_SECRET_ACCESS_KEY
        value: password
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: laravel-bucket
      - key: AWS_ENDPOINT
        fromService: minio

  # --- PostgreSQL ---
  - type: pserv
    name: postgres
    env: docker
    image: postgres:17.2
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: laravel
      - key: POSTGRES_USER
        value: laravel
      - key: POSTGRES_PASSWORD
        value: laravel
    disk:
      name: pgsql-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # --- Redis ---
  - type: pserv
    name: redis
    env: docker
    image: redis:7
    plan: free

  # --- MinIO ---
  - type: pserv
    name: minio
    env: docker
    image: minio/minio:latest
    plan: free
    envVars:
      - key: MINIO_ROOT_USER
        value: sail
      - key: MINIO_ROOT_PASSWORD
        value: password
    disk:
      name: minio-data
      mountPath: /data/minio
      sizeGB: 1
    startCommand: minio server /data/minio --console-address ":8900"
